version: "3.8"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./api:/app
    command:
      - /app/boot.sh
    
  admin:
    build:
      context: admin
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./admin:/app
    command:
      - /app/boot.sh
      
  graph:
    build:
      context: graph
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    command:
      - /app/.docker/canopy/boot.sh
    
