import { Dashboard } from './Dashboard.js'
import { Analytics } from './Analytics.js'
import { Pages } from './Pages.js'
import { Edit } from './Edit.js'
import { Inquiries } from './Inquiries.js'
import { Settings } from './Settings.js'

export { default as Dashboard}  from './Dashboard.js'
export { default as Analytics}  from './Analytics.js'
export { default as Pages}  from './Pages.js'
export { default as Edit}  from './Edit.js'
export { default as Inquiries}  from './Inquiries.js'
export { default as Settings}  from './Settings.js'
